config/routes.rb
Rails.application.routes.draw do
  get 'justificatifs/new'
  get 'justificatifs/create'
  devise_for :users
  root to: 'pages#home'
  get 'furnishers', to: 'pages#fournisseurs'

  get 'price', to: 'pages#price'
  get 'brands/:id/pricer', to: 'pages#pricer'

  get 'stocks', to: 'pages#stocks'
  get 'panier', to: 'pages#panier'
  get 'comptabilite', to: 'pages#comptabilite'
  get 'creditdetail', to: 'pages#creditdetail'
  get 'stat', to: 'pages#stat'
  get 'fiche', to: 'pages#fiche'
  get 'repartition', to: 'pages#repartition'
  get 'repartitionage', to: 'pages#repartitionage'
  get 'repartitiongenre', to: 'pages#repartitiongenre'
  get 'venteparsku', to: 'pages#venteparsku'
  get 'inventoryage', to: 'pages#inventoryage'
  get 'pro', to: 'pages#pro'
  get 'caisse', to: 'pages#caisse'

  resources :fournisseurs do
    resources :paiements, only: [ :index, :show, :new, :create]
    resources :justificatifs, only: [:new, :create]
  end

  resources :justificatifs, only: [:edit, :update]
  post 'justificatifs/:id/don', to: "justificatifs#don", as: "don"

  resources :selections do
    resources :products, only: [ :index, :new, :create ]
  end
  resources :products, only: [ :index, :edit, :update, :destroy, :show]
    post 'products/:id/sold', to: "products#sold_status", as: "sold_status"
    post 'products/:id/sell', to: "products#tosell_status", as: "tosell_status"
    post 'products/:id/return', to: "products#return_status", as: "return_status"
    post 'products/:id/edit_price', to: "products#edit_price", as: "edit_price"
    post 'products/duplicate', to: "products#duplicate", as: "duplicate"
    post 'products/import', to: "products#import", as: "import"
    get 'products/:id/stock4pro', to: "products#stock4pro", as: "stock4pro"
    get 'products/:id/select4pro', to: "products#select4pro", as: "select4pro"
    get 'products/:id/qrcode', to: "products#qrcode", as: "qrcode"

  resources :paiements, only: [ :edit, :update, :destroy]
    post 'paiements/:id/settle', to: "paiements#settle_status", as: "settle_status"
    post 'paiements/avoir', to: "paiements#avoir", as: "avoir"
    post 'paiements/:id/edit_amount', to: "paiements#edit_amount", as: "edit_amount"

  get 'fournisseurs/:id/save_csv', to: "fournisseurs#save_csv", as: "fournisseur_save_csv"

  get 'selections/:id/csv', to: "selections#csv", as: "selection_csv"
  get 'selections/:id/mail', to: "selections#mail", as: "selection_mail"
  get 'selections/:id/summary', to: "selections#summary", as: "selection_summary"
  get 'selections/:id/return', to: "selections#return", as: "selection_return"
  get 'selections/:id/etiquette', to: "selections#etiquette", as: "selection_etiquette"
  get 'carts/devis', to: "carts#devis", as: "devis"

  resources :brands
  resources :clothes
  resources :colors
  resources :tarifs
    get 'brands/:id/tarifsbybrand', to: "tarifs#tarifsbybrand", as: "tarifsbybrand"
    get 'brands/research', to: "brands#research", as: "research"

  post 'products/:id/save_price', to: "products#save_price", as: "save_price"

  # resources :sessions
  post 'sessions/display', to: "sessions#display", as: "display"
  post 'sessions/list', to: "sessions#list", as: "list"
  get 'sessions/validation', to: "sessions#validation", as: "validation"
  get 'products/:id/add_to_list', to: "products#add_to_list", as: "add_to_list"
  get 'products/:id/delete_to_list', to: "products#delete_to_list", as: "delete_to_list"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/selection.rb
class Selection < ApplicationRecord
  belongs_to :fournisseur

  has_many :products, dependent: :destroy
  has_one :notification, dependent: :destroy

  def sum_up
    sum = 0
    self.products.each do |product|
      # product price is all taxes included
      sum += product.price / 1.2
    end
    return sum
  end

  def sum_up_for_fournisseur
    sum = 0
    my_date = "2022-02-13".to_date
    self.products.each do |product|
      # apply this new calculation if my product date is > "2021-02-13"
      if product.created_at.to_date > my_date
        # product price is all taxes included
        # cette fonction doit appliquer une commission progressive pour le client selon le prix du vetement.
        if product.price >= 50.to_money
          # 70% du prix HT
          sum += (product.price/1.2) * 0.7
        elsif product.price >= 30.to_money
          # 60% du prix HT
          sum += (product.price/1.2) * 0.6
        else
          # 50% du prix HT
          sum += (product.price/1.2) * 0.5
        end
      else
        sum += (product.price/1.2) * 0.5
      end
    end
    return sum
  end

  def gain
    sum = 0
    my_date = "2022-02-13".to_date
    self.products.where(status: "vendu").each do |product|
      # apply this new calculation if my product date is > "2021-02-13"
      if product.created_at.to_date > my_date
        if product.price >= 50.to_money
          # 70% du prix HT
          sum += (product.price/1.2) * 0.7
        elsif product.price >= 30.to_money
          # 60% du prix HT
          sum += (product.price/1.2) * 0.6
        else
          # 50% du prix HT
          sum += (product.price/1.2) * 0.5
        end
      else
        sum += (product.price/1.2) * 0.5
      end
    end
    return sum
  end

  def generate_csv
    csv_options = { col_sep: ',', encoding: 'ISO-8859-1'}
    CSV.generate(csv_options) do |csv|
      csv << ["Handle","Title","Body (HTML)","Vendor","Type","Tags","Published","Option1 Name","Option1 Value","Option2 Name","Option2 Value","Option3 Name","Option3 Value","Variant SKU","Variant Grams","Variant Inventory Tracker","Variant Inventory Qty","Variant Inventory Policy","Variant Fulfillment Service","Variant Price","Variant Compare At Price","Variant Requires Shipping","Variant Taxable","Variant Barcode","Image Src","Image Position","Image Alt Text","Gift Card","SEO Title","SEO Description","Google Shopping / Google Product Category","Google Shopping / Gender","Google Shopping / Age Group","Google Shopping / MPN","Google Shopping / AdWords Grouping","Google Shopping / AdWords Labels","Google Shopping / Condition","Google Shopping / Custom Product","Google Shopping / Custom Label 0","Google Shopping / Custom Label 1","Google Shopping / Custom Label 2","Google Shopping / Custom Label 3","Google Shopping / Custom Label 4","Variant Image","Variant Weight Unit","Variant Tax Code","Cost per item"]
      self.products.each do |product|
        if product.status == "à vendre" && product.photo.present?
        image_url = "http://res.cloudinary.com/grainedemomes/image/upload/" + product.photo.key.to_s
        csv << ["#{product.name}-#{product.id}","#{product.name} #{product.brand} #{product.size}","<meta content='text/html charset=utf-8'' http-equiv=''content-type''><span data-mce-fragment=''1''>Occasion - #{product.comment}.<br>Cet article est unique.1 seul exemplaire est en stock.<br>#{product.commentaire}</span>","#{product.brand}","#{product.category}","#{product.genre}","true","Taille","#{product.size}","Saison","#{product.season}","","","#{product.id}","0.0","shopify",1,"deny","manual","#{product.price}","","true","true","","#{image_url}",1,"","false","","","","","","","","","","","","","","","","#{image_url}","kg","",""]
        # PENSER A INDIQUER LE PRIX EN TTC ET PAS SUR LA BASE HT
        end
      end
    end
  end

  def percentage_sold
    result = 0.to_f
    total = self.products.all.count.to_f
    self.products.each do |product|
      if product.status == "vendu"
        result += 1
      end
    end
    percentage = (result / total) * 100
    return percentage
  end

end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  require 'date'
  require 'csv'


  def index
    @fournisseur = Fournisseur.find(params[:fournisseur_id])
    @selections = @fournisseur.selections
    authorize @selections
  end

  def show
    @selection = Selection.find(params[:id])
    authorize @selection
    @fournisseur = @selection.fournisseur_id
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Sélection N°. #{@selection.id} de #{@selection.fournisseur.firstname} #{@selection.fournisseur.lastname} du #{@selection.date}.",
          layout: 'pdf.html',
          page_size: 'A4',
          template: "selections/show.html.erb",
          background: false,
          no_background: true,
          lowquality: true,
          zoom: 1,
          dpi: 300,
          encoding:"UTF-8"
      end
    end
  end

  def etiquette
    @selection = Selection.find(params[:id])
    authorize @selection
    @fournisseur = @selection.fournisseur_id
    @products = @selection.products.where(status: "à vendre")
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Etiquettes de la Sélection N°. #{@selection.id}.",
          layout: 'pdf2.html',
          page_size: 'A4',
          template: "selections/show.html.erb",
          background: false,
          no_background: true,
          lowquality: true,
          zoom: 1,
          dpi: 300,
          encoding:"UTF-8"
      end
    end
  end

  def new
    @selection = Selection.new
    authorize @selection
  end

  def create
    @selection = Selection.new
    authorize @selection
    @selection.date = Date.today.strftime("%d/%m/%Y")
    @selection.fournisseur = Fournisseur.find(params[:fournisseur_id])
    @selection.user_id = @selection.fournisseur.user_id
    @selection.save
    redirect_to selection_path(@selection)
  end

  def edit
    @selection = Selection.find(params[:id])
    authorize @selection
    @fournisseur = @selection.fournisseur_id
  end

  def destroy
    @selection = Selection.find(params[:id])
    authorize @selection
    @selection.destroy
    redirect_to selections_path(fournisseur_id: @selection.fournisseur.id)
  end

  def csv
    @selection = Selection.find(params[:id])
    authorize @selection
    # prepare my csv with Model function
    csv = @selection.generate_csv
    # prepare email and forward csv as argument
    ProposalMailer.generatecsv(csv).deliver_now
    redirect_to selection_path(@selection)
    flash[:notice] = "le CSV a bien été transmis."
  end

  def mail
    @selection = Selection.find(params[:id])
    authorize @selection
    # prepare email and forward csv as argument
    #ProposalMailer.information(@selection).deliver_now
    ProposalMailer.proposal(@selection).deliver_now
    @notification = Notification.new(selection_id: @selection.id)
    @notification.status = "transmis"
    @notification.save!
    redirect_to selections_path(fournisseur_id: @selection.fournisseur.id)
    flash[:notice] = "l'Email a été expédié."
  end

  def summary
    @selection = Selection.find(params[:id])
    authorize @selection
    # prepare email and forward csv as argument
    #ProposalMailer.information(@selection).deliver_now
    ProposalMailer.summary(@selection).deliver_now
    redirect_to selections_path(fournisseur_id: @selection.fournisseur.id)
    flash[:notice] = "l'Email a été expédié."
  end

  def return
    @selection = Selection.find(params[:id])
    authorize @selection
    @selection.return = true
    @selection.save!
    redirect_to selections_path(fournisseur_id: @selection.fournisseur.id)
    flash[:notice] = "Status sauvegardé"
  end

  private

  def selection_params
    params.require(:selection).permit(:date, :fournisseur_id, :user_id)
  end
end

app/views/selections/_image.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
   <div class="modal-content form-content">
     <div class="modal-header form-content">
       <button type="button" class="close" data-dismiss="modal" aria-label="Close">
         <span aria-hidden="true">&times;</span>
       </button>
     </div>
     <div class="modal-body">
       <div class="container">
          <% if @product.present? %>
            <%= cl_image_tag @product.photo.key, class: "w-50"%>
          <% else %>
            <p>Ce produit ne contient pas d'image.</p>
          <% end %>
       </div>
     </div>
   </div>
  </div>
</div>

app/views/selections/index.html.erb
<div style="margin: 32px;">
  <h1>Les sélections de <%= @fournisseur.firstname %> <%= @fournisseur.lastname %></h1>
  <%= link_to 'Retour au fournisseur', fournisseur_path(@fournisseur), class: "btn button-red", style:"margin-bottom: 16px;"%>
  <%= link_to 'retour au Menu', root_path, class: "button-sm"%>
</div>
<div class="table-selections">
  <table style="border: 1px solid black; font-weight: bolder;">
    <tr>
      <td>Date de la sélection</td>
      <td>Nombre de produits</td>
      <td>% vendu</td>
      <td>Actions disponibles</td>
      <td>Mail transmis</td>
      <td>Retournée ?</td>
    </tr>
  <% @fournisseur.selections.each do |selection| %>
    <% if selection.return %>
      <tr style="background-color: rgba(228,193,249) !important;">
        <td><%= selection.date %> </td>
        <td><%= selection.products.count %> produits</td>
        <% if selection.percentage_sold > 0 %>
          <td><%= selection.percentage_sold.to_i %>%</td>
        <% else %>
          <td>0%</td>
        <% end %>
        <td style="height: 20vh; display: flex; flex-direction: column; justify-content: space-between;">
          <%= link_to 'Voir sa sélection', selection_path(selection), class: "button"%> <%= link_to "Envoyer la proposition", selection_mail_path(selection), id: "delete-link", class: "button-red", data: {confirm: "Vous confirmez l'envoi ?"}  %> <%= link_to 'Supprimer', selection_path(selection), method: :delete, class: "button-red "%>
        </td>
        <td>
          <% if selection.notification.present? && selection.notification.status == "transmis"%>
            <i class="fas fa-check-circle" id="green"></i>
          <% else %>
            <i class="fas fa-times-circle" id="red"></i>
          <% end %>
        </td>
        <td>
          <% if selection.return %>
            <i class="far fa-hand-point-left"></i>
          <% end %>
        </td>
      </tr>
    <% else %>
      <tr>
        <td><%= selection.date %> </td>
        <td><%= selection.products.count %> produits</td>
        <% if selection.percentage_sold > 0 %>
          <td><%= selection.percentage_sold.to_i %>%</td>
        <% else %>
          <td>0%</td>
        <% end %>
        <td style="height: 20vh; display: flex; flex-direction: column; justify-content: space-between;">
          <%= link_to 'Voir sa sélection', selection_path(selection), class: "button"%> <%= link_to "Envoyer la proposition", selection_mail_path(selection), id: "delete-link", class: "button-red", data: {confirm: "Vous confirmez l'envoi ?"}  %> <%= link_to 'Supprimer', selection_path(selection), method: :delete, class: "button-red "%>
        </td>
        <td>
          <% if selection.notification.present? && selection.notification.status == "transmis"%>
            <i class="fas fa-check-circle" id="green"></i>
          <% else %>
            <i class="fas fa-times-circle" id="red"></i>
          <% end %>
        </td>
        <td>
          <% if selection.return %>
            <i class="far fa-hand-point-left"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
  </table>
</div>

app/views/selections/show.html.erb
<div style="min-height: 100vh; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('../assets/train.jpg'); background-size: cover; background-position: center;">
  <div class="m-5" style="color: white!important;">
    <h1>Détail de la sélection n°<%= @selection.id %> de <%= @selection.fournisseur.firstname %></h1>
    <div class="buttons-fournisseurs">
      <% if @selection.products.count > 0  && current_user.admin %>
        <%= link_to "Générer un PDF", selection_path(@selection, :format => :pdf) , :format => :pdf, class: "btn btn-success" %>
        <%= link_to "Etiquettes", selection_etiquette_path(@selection, :format => :pdf) , :format => :pdf, class: "btn btn-success" %>
        <%= link_to "Envoyer un récapitulatif", selection_summary_path, class: "button-red", style:"width: 240px;", data: {confirm: "Vous confirmez l'envoi ?"} %>
        <%= link_to "Enregistrer en CSV", selection_csv_path, class: "button-red", style:"width: 240px;" %>
        <%= link_to 'Ajouter un produit', new_selection_product_path(@selection), class: "btn btn-primary"%>
        <%= link_to 'Retour', selections_path(fournisseur_id: @selection.fournisseur.id), class: "btn btn-success"%>
        <h3><%= @selection.products.count %> produit(s)</h3>
      <% elsif current_user.admin %>
        <%= link_to 'Ajouter un produit', new_selection_product_path(@selection), class: "btn btn-primary"%>
        <%= link_to 'Retour', selections_path(fournisseur_id: @selection.fournisseur.id), class: "btn btn-success"%>
        <h3><%= @selection.products.count %> produit(s)</h3>
      <% else %>
        <%= link_to 'Retour', root_path, class: "btn btn-success"%>
        <h3><%= @selection.products.count %> produit(s)</h3>
      <% end %>
    </div>
    <div style="margin-left: 8px; margin-top: 8px;">
      <% if @selection.products.count > 0  && current_user.admin %>
        <%= link_to "Retourner la sélection", selection_return_path, class: "button-red", style:"width: 240px;", data: {confirm: "Vous confirmez le retour ?"} %>
      <% end %>
    </div>
  </div>
  <div class="products_table">
    <% if current_user.admin %>
      <div id="button-plus">
        <%= link_to '+', duplicate_path, method: :post %>
        <p>dupliquer le dernier produit</p>
      </div>
    <% end %>
    <table style="color: white !important; font-weight: bolder;">
      <tr id="product-bg">
        <% if current_user.admin %>
          <td>N°</td>
        <% end %>
        <td>Vêtements</td>
        <td>Marque</td>
        <td id="responsivity">Catégorie</td>
        <td>Taille</td>
        <% if current_user.admin %>
          <td id="responsivity">Genre</td>
        <% end %>
        <td>Couleur</td>
        <% if current_user.admin %>
          <td id="responsivity">Prix HT</td>
        <% end %>
        <td id="responsivity">Prix TTC</td>
        <td>Statut</td>
        <% if current_user.admin %>
          <td>Photo</td>
          <td id="responsivity">MAJ prix</td>
          <td>Editer</td>
          <td id="responsivity">Supprimer</td>
          <td id="responsivity">Vendu ?</td>
        <% end %>
      </tr>
      <% if @selection.products.count > 0 %>
        <% @selection.products.order(:id).each do |product| %>
          <% if product.status == "vendu" %>
            <tr id="product-details-vendu">
              <% if current_user.admin %>
                <td><%= product.id %></td>
              <% end %>
              <td><%= product.name %></td>
              <td><%= product.brand %></td>
              <td id="responsivity"><%= product.category %></td>
              <td><%= product.size %></td>
              <% if current_user.admin %>
                <td id="responsivity"><%= product.genre %></td>
              <% end %>
              <td><%= product.color %></td>
              <% if current_user.admin %>
                <td id="responsivity"><%= product.price / 1.2 %>€</td>
              <% end %>
              <td id="responsivity"><%= product.price %>€</td>
              <td><%= product.status %></td>
              <% if current_user.admin %>
                <td>
                  <% if product.photo.present?%>
                    <%= link_to product_path(product) do %>
                      <i class="fas fa-camera-retro"></i>
                    <% end %>
                  <% else %>
                    <i class="fas fa-ban" style="color: #9E2725;"></i>
                  <% end %>
                </td>
                <td id="responsivity">
                  <% if product.status == "à vendre" %>
                    <%= link_to '€', edit_price_path(product), method: :post %>
                  <% else %>
                    <i class="fas fa-ban" style="color: #9E2725;"></i>
                  <% end %>
                </td>
                <td>
                  <% if product.status == "à vendre" %>
                    <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_product_path(product)%>
                  <% else %>
                    <i class="fas fa-ban" style="color: #9E2725;"></i>
                  <% end %>
                </td>
                <td id="responsivity">
                  <% if product.status == "à vendre" %>
                    <%= link_to '<i class="fas fa-trash"></i>'.html_safe, product_path(product), method: :delete, data: {confirm: "Vous êtes sûre?"} %>
                  <% else %>
                    <i class="fas fa-ban" style="color: #9E2725;"></i>
                  <% end %>
                </td>
                <td id="responsivity">
                  <%= link_to '<i class="fas fa-cart-arrow-down"></i>'.html_safe, sold_status_path(product), method: :post, style:"color: green;" %> / <%= link_to '<i class="fas fa-undo"></i>'.html_safe, tosell_status_path(product), method: :post, style:"color: #F6AE3B;" %>
                </td>
              <% end %>
            </tr>
          <% else %>
            <tr id="product-details">
              <% if current_user.admin %>
                <td><%= product.id %></td>
              <% end %>
              <td><%= product.name %></td>
              <td><%= product.brand %></td>
              <td id="responsivity"><%= product.category %></td>
              <td><%= product.size %></td>
              <% if current_user.admin %>
                <td id="responsivity"><%= product.genre %></td>
              <% end %>
              <td><%= product.color %></td>
              <% if current_user.admin %>
                <td id="responsivity"><%= product.price / 1.2 %>€</td>
              <% end %>
              <td id="responsivity"><%= product.price %>€</td>
              <td><%= product.status %></td>
              <% if current_user.admin %>
                <td>
                  <% if product.photo.present?%>
                    <%= link_to product_path(product) do %>
                      <i class="fas fa-camera-retro"></i>
                    <% end %>
                  <% else %>
                    <i class="fas fa-ban" style="color: #9E2725;"></i>
                  <% end %>
                </td>
                <td id="responsivity">
                  <% if product.status == "à vendre" %>
                    <%= link_to '€', edit_price_path(product), method: :post %>
                  <% else %>
                    <i class="fas fa-ban" style="color: #9E2725;"></i>
                  <% end %>
                </td>
                <td>
                  <% if product.status == "à vendre" %>
                    <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_product_path(product)%>
                  <% else %>
                    <i class="fas fa-ban" style="color: #9E2725;"></i>
                  <% end %>
                </td>
                <td>
                  <% if product.status == "à vendre" %>
                    <%= link_to '<i class="fas fa-trash"></i>'.html_safe, product_path(product), method: :delete, data: {confirm: "Vous êtes sûre?"} %>
                  <% else %>
                    <i class="fas fa-ban" style="color: #9E2725;"></i>
                  <% end %>
                </td>
                <td id="responsivity">
                  <%= link_to '<i class="fas fa-cart-arrow-down"></i>'.html_safe, sold_status_path(product), method: :post, style:"color: green;" %> / <%= link_to '<i class="fas fa-undo"></i>'.html_safe, tosell_status_path(product), method: :post, style:"color: #F6AE3B;" %>
                </td>
                <td id="responsivity">
                  <% if Tarif.where(brand: product.brand, clothe: product.name).present? %>
                  <% else %>
                    <%= link_to '<i class="fas fa-save"></i>'.html_safe, save_price_path(product), method: :post %>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
        <% else %>
          <tr style="color: white !important; font-weight: bolder;"> Cette sélection ne contient pas de produit.</tr>
        <% end %>
    </table>
  </div>
  <a href="" id="arrow"><i class="fas fa-arrow-up"></i></a>
</div>