config/routes.rb
Rails.application.routes.draw do
  get 'justificatifs/new'
  get 'justificatifs/create'
  devise_for :users
  root to: 'pages#home'
  get 'furnishers', to: 'pages#fournisseurs'

  get 'price', to: 'pages#price'
  get 'brands/:id/pricer', to: 'pages#pricer'

  get 'stocks', to: 'pages#stocks'
  get 'panier', to: 'pages#panier'
  get 'comptabilite', to: 'pages#comptabilite'
  get 'creditdetail', to: 'pages#creditdetail'
  get 'stat', to: 'pages#stat'
  get 'fiche', to: 'pages#fiche'
  get 'repartition', to: 'pages#repartition'
  get 'repartitionage', to: 'pages#repartitionage'
  get 'repartitiongenre', to: 'pages#repartitiongenre'
  get 'venteparsku', to: 'pages#venteparsku'
  get 'inventoryage', to: 'pages#inventoryage'
  get 'pro', to: 'pages#pro'
  get 'caisse', to: 'pages#caisse'

  resources :fournisseurs do
    resources :paiements, only: [ :index, :show, :new, :create]
    resources :justificatifs, only: [:new, :create]
  end

  resources :justificatifs, only: [:edit, :update]
  post 'justificatifs/:id/don', to: "justificatifs#don", as: "don"

  resources :selections do
    resources :products, only: [ :index, :new, :create ]
  end
  resources :products, only: [ :index, :edit, :update, :destroy, :show]
    post 'products/:id/sold', to: "products#sold_status", as: "sold_status"
    post 'products/:id/sell', to: "products#tosell_status", as: "tosell_status"
    post 'products/:id/return', to: "products#return_status", as: "return_status"
    post 'products/:id/edit_price', to: "products#edit_price", as: "edit_price"
    post 'products/duplicate', to: "products#duplicate", as: "duplicate"
    post 'products/import', to: "products#import", as: "import"
    get 'products/:id/stock4pro', to: "products#stock4pro", as: "stock4pro"
    get 'products/:id/select4pro', to: "products#select4pro", as: "select4pro"
    get 'products/:id/qrcode', to: "products#qrcode", as: "qrcode"

  resources :paiements, only: [ :edit, :update, :destroy]
    post 'paiements/:id/settle', to: "paiements#settle_status", as: "settle_status"
    post 'paiements/avoir', to: "paiements#avoir", as: "avoir"
    post 'paiements/:id/edit_amount', to: "paiements#edit_amount", as: "edit_amount"

  get 'fournisseurs/:id/save_csv', to: "fournisseurs#save_csv", as: "fournisseur_save_csv"

  get 'selections/:id/csv', to: "selections#csv", as: "selection_csv"
  get 'selections/:id/mail', to: "selections#mail", as: "selection_mail"
  get 'selections/:id/summary', to: "selections#summary", as: "selection_summary"
  get 'selections/:id/return', to: "selections#return", as: "selection_return"
  get 'selections/:id/etiquette', to: "selections#etiquette", as: "selection_etiquette"
  get 'carts/devis', to: "carts#devis", as: "devis"

  resources :brands
  resources :clothes
  resources :colors
  resources :tarifs
    get 'brands/:id/tarifsbybrand', to: "tarifs#tarifsbybrand", as: "tarifsbybrand"
    get 'brands/research', to: "brands#research", as: "research"

  post 'products/:id/save_price', to: "products#save_price", as: "save_price"

  # resources :sessions
  post 'sessions/display', to: "sessions#display", as: "display"
  post 'sessions/list', to: "sessions#list", as: "list"
  get 'sessions/validation', to: "sessions#validation", as: "validation"
  get 'products/:id/add_to_list', to: "products#add_to_list", as: "add_to_list"
  get 'products/:id/delete_to_list', to: "products#delete_to_list", as: "delete_to_list"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/fournisseur.rb
class Fournisseur < ApplicationRecord
  has_many :selections, dependent: :destroy
  has_many :products, through: :selections
  has_many :paiements
  has_one :justificatif, dependent: :destroy

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: false, uniqueness: true
  validates :rib, presence: false

  def sold
    sold = 0
    self.selections.each do |selection|
      selection.products.where(status: "vendu").each do |product|
        sold += ((product.price/1.2) * 0.5)
      end
    end
    return sold
  end

  def inventory
    sold = 0
    self.selections.each do |selection|
      selection.products.each do |product|
        sold += (product.price/1.2)
      end
    end
    return sold
  end

  def total
    sold = 0
    self.selections.each do |selection|
      selection.products.each do |product|
        sold += 1
      end
    end
    return sold
  end

  def settle
    sum = 0
    self.paiements.where(status: "généré").each do |element|
      sum += element.amount
    end
    return sum
  end

  def credit
    credit = self.sold.to_f - (self.settle * 100).to_f
    return credit.to_i
  end

  def sales
    self.count
  end

  def save_fournisseur_csv
    csv_options = { col_sep: ',', encoding: 'ISO-8859-1'}
    CSV.generate(csv_options) do |csv|
      csv << ["EMAIL DES FOURNISSEURS"]
      Fournisseur.all.each do |fournisseur|
        csv << ["#{fournisseur.email}"]
      end
      csv << ["FOURNISSEUR"]
      Fournisseur.all.each do |fournisseur|
        csv << ["f = Fournisseur.new(id: #{fournisseur.id}, firstname: '#{fournisseur.firstname}', lastname: '#{fournisseur.lastname}', rib: '#{fournisseur.rib}', email: '#{fournisseur.email}', phone: '#{fournisseur.phone}', code: '#{fournisseur.code}')"]
        csv << ["f.save!"]
      end
      Selection.all.each do |selection|
        csv << ["s = Selection.new(id: #{selection.id}, date: '#{selection.date}', fournisseur_id: #{selection.fournisseur_id})"]
        csv << ["s.save!"]
      end
      Product.order("id ASC").each do |product|
          csv << ["p = Product.new(id: #{product.id}, brand: '#{product.brand}', name: '#{product.name}', size: '#{product.size}', color: '#{product.color}', status: '#{product.status}', price_cents: #{product.price_cents}, price_currency: 'EUR', selection_id: #{product.selection_id})"]
          csv << ["p.save!"]
      end
      User.all.each do |user|
        csv << ["u = User.new(id: #{user.id}, email: '#{user.email}', admin: #{user.admin}, pro: #{user.pro})"]
        csv << ["u.save!"]
      end
      Justificatif.all.each do |element|
        csv << ["u = Justificatif.new(id: #{element.id}, justif: '#{element.justif}', fournisseur_id: #{element.fournisseur_id})"]
        csv << ["u.save!"]
      end
    end
  end

  def save_fournisseur_csv2
    csv_options = { col_sep: ',', encoding: 'ISO-8859-1'}
    CSV.generate(csv_options) do |csv|
      csv << ["N°id","Type","Marque","Taille","Genre","Prix HT","Prix KIABI"]
      Product.order("id ASC").each do |product|
        if product.status == "à vendre"
          csv << ["#{product.id}","#{product.name}","#{product.brand}","#{product.size}","#{product.genre}","#{product.price*1.2}","#{product.price*0.96}"]
        end
      end
      csv << [" "]
      csv << ["la liste des fournisseurs"]
      csv << [" "]
      csv << ["ID","Prénom","Nom","email","téléphone"]
      Fournisseur.order("id ASC").each do |fournisseur|
        selection = Selection.where(fournisseur: fournisseur.id).count
        csv << ["#{fournisseur.id}","#{fournisseur.firstname}","#{fournisseur.lastname}","#{fournisseur.email}","#{fournisseur.phone}","#{selection} selections(s)"]
      end
    end
  end

  # def save_product_csv
  #   csv_options = { col_sep: ',', encoding: 'ISO-8859-1'}
  #   CSV.generate(csv_options) do |csv|
  #     range = (1..7000).to_a
  #     range.each do |number|
  #       if Product.where(id: number).present? == false
  #       # Product.order("id ASC").each do |product|
  #         csv << ["p = Product.new(id: #{number}, price_cents: 0, price_currency: 'EUR', selection_id: 217)"]
  #         csv << ["p.save!"]
  #       end
  #     end
  #   end
  # end

  #pg search
  include PgSearch::Model
  pg_search_scope :search_by_lastname_email_code,
    against: [ :lastname, :email, :code ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/fournisseurs_controller.rb
class FournisseursController < ApplicationController
  require 'date'
  require 'csv'

  def index
    if params[:query].present?
      @fournisseurs = Fournisseur.search_by_lastname_email_code(params[:query])
    else
      @fournisseurs = Fournisseur.where(user_id: current_user.id).all
      # @fournisseurs = Fournisseur.all
    end
    if @fournisseurs.count == 0
      # @fournisseurs = Fournisseur.all
      @fournisseurs = Fournisseur.where(user_id: current_user.id).all
    end
    authorize @fournisseurs
  end

  # def index
  #   @fournisseurs = Fournisseur.all
  # end

  def show
    @fournisseur = Fournisseur.find(params[:id])
    authorize @fournisseur
    @selections = @fournisseur.selections
    @total = 0
    @sumup = 0
    @selections.each do |selection|
      @total += selection.products.count
      selection.products.each do |product|
        @sumup += product.price
      end
    end
    return @total
    return @sumup
  end

  def new
    @fournisseur = Fournisseur.new
    authorize @fournisseur
  end

  def create
    @fournisseur = Fournisseur.new(fournisseur_params)
    authorize @fournisseur
    numberforcode = (10000 - Fournisseur.count).to_s
    @fournisseur.code = Date.today.year.to_s + @fournisseur.firstname.chr + @fournisseur.lastname.chr + numberforcode
    @fournisseur.firstname = @fournisseur.firstname.capitalize
    @fournisseur.lastname = @fournisseur.lastname.capitalize
    @fournisseur.user_id = current_user.id
    if @fournisseur.save
      redirect_to furnishers_path
      flash[:notice] = "Votre fournisseur a bien été enregistré."
    else
      render :new
      flash[:alert] = "Veuillez compléter le formulaire s'il vous plaît."
    end
  end

  def edit
    @fournisseur = Fournisseur.find(params[:id])
    authorize @fournisseur
  end

  def update
    @fournisseur = Fournisseur.find(params[:id])
    authorize @fournisseur
    if @fournisseur.update(fournisseur_params)
      redirect_to fournisseur_path(@fournisseur)
    else render :edit
    end
  end

  def destroy
    @fournisseur = Fournisseur.find(params[:id])
    authorize @fournisseur
    @fournisseur.destroy
    redirect_to fournisseurs_path
  end

  def add_justif
    @fournisseur = Fournisseur.find(params[:id])
    # authorize @fournisseur
    if @fournisseur.update(fournisseur_justif_params)
      redirect_to root_path
    else render :justif
    end
  end

  def save_csv
    @fournisseur = Fournisseur.find(params[:id])
    authorize @fournisseur
    # prepare my csv with Model function
    csv = @fournisseur.save_fournisseur_csv2
    # prepare email and forward csv as argument
    ProposalMailer.fournisseurcsv(csv).deliver_now
    # prepare my csv with Model function
    # csv2 = @fournisseur.save_product_csv
    # # prepare email and forward csv as argument
    # ProposalMailer.fournisseurcsv(csv2).deliver_now
    redirect_to root_path
    flash[:notice] = "le CSV a bien été transmis."
  end

  private

  def fournisseur_params
    params.require(:fournisseur).permit(:firstname, :lastname, :email, :phone, :rib, :code, :user_id)
  end

  def fournisseur_justif_params
    params.require(:fournisseur).permit(:justif)
  end
end

app/views/fournisseurs/edit.html.erb
<div class="fiche_fournisseur">
  <%= link_to 'retour aux fournisseurs', fournisseurs_path, class: "btn btn-success"%>
  <br>
  <br>
  <h1>Editez ce fournisseur</h1>
   <%= simple_form_for(@fournisseur) do |f| %>
      <%= f.input :firstname, label: 'Prénom', placeholder: "Freddy" %>
      <%= f.input :lastname, label: 'Nom de famille', placeholder: "Mercury" %>
      <%= f.input :email, label: 'adresse e-mail', placeholder: "bonjour@grainedemomes.com" %>
      <%= f.input :phone, label: 'Téléphone', placeholder: "0636373637" %>
      <%= f.input :rib, label: 'RIB', placeholder: "FR76XXXXXXXX" %>
      <%= f.submit "Enregistrer", class: 'btn btn-primary' %>
   <% end %>
</div>

app/views/fournisseurs/index.html.erb
<div class="container m-5">
  <%= link_to 'retour au Menu', root_path, class: "button-sm"%>
  <br>
  <%= link_to 'Créer un fournisseur', new_fournisseur_path, class: "button-red", style:"margin-top: 16px;"%>

  <div class="search mt-2">
    <%= form_tag fournisseurs_path, method: :get, novalidate: "novalidate", class: "simple_form search"  do %>
      <div class="search-form-control form-group mt-1 mb-0">
        <%= text_field_tag :query,
            params[:query],
            class: "search-input form-control string required",
            id: "search_query",
            placeholder: "chercher un fournisseur par son nom, son email ou son code",
            value: ""
        %>
        <%= button_tag(type: "submit", class: "btn btn-flat") do %>
          <i class="fas fa-search"></i>
        <% end %>
      </div>
    <% end %>
  </div>

  <% @fournisseurs.each do |element| %>
    <div class="index mt-5">
      <div>
        <%= link_to fournisseur_path(element) do %>
          <%= element.firstname %> <%= element.lastname %>- n°<%= element.code %>
        <% end %>
        <% element.selections.each do |selection| %>
          <% if selection.return == false %>
            <% if selection.percentage_sold == 100 %>
              <%= link_to selections_path(fournisseur_id: element.id) do %>
                <i class="fas fa-star flash-star" style="color: #2DD881;"></i>
              <% end %>
            <% elsif selection.percentage_sold >= 50 %>
              <i class="fas fa-star-half-alt" style="color: #FFD700;"></i>
            <% else %>
              <i class="far fa-star" style="color: #FFD700;"></i>
            <% end %>
          <% else %>
            <i class="fas fa-star" style="color: #FF3C38;"></i>
          <% end %>
        <% end %>
      </div>
      <div>
        <%= link_to 'X', fournisseur_path(element), method: :delete, class: "button-red"%>
      </div>
    </div>
  <% end %>
</div>
<a href="" id="arrow"><i class="fas fa-arrow-up"></i></a>

app/views/fournisseurs/new.html.erb
<div class="fiche_fournisseur">
  <h1>Nouveau fournisseur</h1>
   <%= link_to 'retour au Menu', root_path, class: "button"%>
  <% new_fournisseur = Fournisseur.new %>
 <%= simple_form_for(new_fournisseur) do |f| %>
    <%= f.input :firstname, label: 'Prénom', placeholder: "Freddy" %>
    <%= f.input :lastname, label: 'Nom de famille', placeholder: "Mercury" %>
    <%= f.input :email, label: 'adresse e-mail', placeholder: "bonjour@grainedemomes.com" %>
    <%= f.input :phone, label: 'Téléphone', placeholder: "0636373637" %>
    <%= f.input :rib, label: 'RIB', placeholder: "FR76XXXXXXXX" %>
    <%= f.submit "Créer le fournisseur", class: 'btn btn-primary' %>

 <% end %>
</div>

app/views/fournisseurs/show.html.erb
<div>
  <div class="fiche_fournisseur">
    <h2 style="display: flex;">Fiche de <%= @fournisseur.firstname %> <%= @fournisseur.lastname %>    <%= link_to 'Editer', edit_fournisseur_path(@fournisseur), class: "button", style:"margin-left: 16px;"%></h2>
    <p>Coordonnées : <%= @fournisseur.email %>  / Tél: <%= @fournisseur.phone %></p>
    <% if @fournisseur.justificatif.present? %>
      <p>IBAN: <%= @fournisseur.justificatif.justif %></p>
    <% else %>
      <p>Le fournisseur n'a pas encore saisie son RIB.</p>
    <% end %>
    <% if @fournisseur.justificatif.present? && @fournisseur.justificatif.don %>
      <p>En cas de vêtements invendus : en faire don.</p>
    <% else %>
      <p>En cas de vêtements invendus : récuperer.</p>
    <% end %>
    <p>Code : <%= @fournisseur.code %></p>
    <div>
      <p><%= @selections.count %> sélection(s) - <%= @total %> produit(s) d'une valeur totale de <%= @sumup %> € TTC. Crédit = <%= @fournisseur.credit %> €. </p>
      <% if @fournisseur.paiements.count < 1 %>
        <p>Aucun paiement n'a été réalisé</p>
      <% else %>
        <p>Ses paiements : </p>
        <% @fournisseur.paiements.each do |paiement| %>
          <% if paiement.avoir %>
            <p><%= paiement.date.to_date.strftime("le %d/%m/%Y")%>, un avoir utilisé de <%= paiement.amount_cents %>€</p>
          <% else %>
            <p><%= paiement.date.to_date.strftime("le %d/%m/%Y")%>, un virement de <%= paiement.amount_cents %>€</p>
          <% end %>
        <% end %>
      <% end %>
      <br>
    </div>
  </div>
  <div style="display: flex; justify-content: space-around; align-items: center;">
    <%= link_to 'Ses sélections', selections_path(fournisseur_id: @fournisseur.id), class: "button"%>

    <%= link_to "Créer une nouvelle sélection de vêtements", selections_path(fournisseur_id: @fournisseur.id), method: :post, class: "button-ts"%>

    <%= link_to "Réaliser un paiement", fournisseur_paiements_path(fournisseur_id: @fournisseur.id), method: :post, class: "button-red"%>

    <%= link_to "Générer un avoir", avoir_path(fournisseur_id: @fournisseur.id), method: :post, class: "button-red"%>

    <%= link_to "Retour aux autres fournisseurs", fournisseurs_path, class: "button-return"%>
  </div>
  <br>
  <%= link_to "Sauvegarder", fournisseur_save_csv_path, class: "button-sm", style:"margin-left: 32px; margin-top: 16px;"%>
</div>