config/routes.rb
Rails.application.routes.draw do
  get 'justificatifs/new'
  get 'justificatifs/create'
  devise_for :users
  root to: 'pages#home'
  get 'furnishers', to: 'pages#fournisseurs'

  get 'price', to: 'pages#price'
  get 'brands/:id/pricer', to: 'pages#pricer'

  get 'stocks', to: 'pages#stocks'
  get 'panier', to: 'pages#panier'
  get 'comptabilite', to: 'pages#comptabilite'
  get 'creditdetail', to: 'pages#creditdetail'
  get 'stat', to: 'pages#stat'
  get 'fiche', to: 'pages#fiche'
  get 'repartition', to: 'pages#repartition'
  get 'repartitionage', to: 'pages#repartitionage'
  get 'repartitiongenre', to: 'pages#repartitiongenre'
  get 'venteparsku', to: 'pages#venteparsku'
  get 'inventoryage', to: 'pages#inventoryage'
  get 'pro', to: 'pages#pro'
  get 'caisse', to: 'pages#caisse'

  resources :fournisseurs do
    resources :paiements, only: [ :index, :show, :new, :create]
    resources :justificatifs, only: [:new, :create]
  end

  resources :justificatifs, only: [:edit, :update]
  post 'justificatifs/:id/don', to: "justificatifs#don", as: "don"

  resources :selections do
    resources :products, only: [ :index, :new, :create ]
  end
  resources :products, only: [ :index, :edit, :update, :destroy, :show]
    post 'products/:id/sold', to: "products#sold_status", as: "sold_status"
    post 'products/:id/sell', to: "products#tosell_status", as: "tosell_status"
    post 'products/:id/return', to: "products#return_status", as: "return_status"
    post 'products/:id/edit_price', to: "products#edit_price", as: "edit_price"
    post 'products/duplicate', to: "products#duplicate", as: "duplicate"
    post 'products/import', to: "products#import", as: "import"
    get 'products/:id/stock4pro', to: "products#stock4pro", as: "stock4pro"
    get 'products/:id/select4pro', to: "products#select4pro", as: "select4pro"
    get 'products/:id/qrcode', to: "products#qrcode", as: "qrcode"

  resources :paiements, only: [ :edit, :update, :destroy]
    post 'paiements/:id/settle', to: "paiements#settle_status", as: "settle_status"
    post 'paiements/avoir', to: "paiements#avoir", as: "avoir"
    post 'paiements/:id/edit_amount', to: "paiements#edit_amount", as: "edit_amount"

  get 'fournisseurs/:id/save_csv', to: "fournisseurs#save_csv", as: "fournisseur_save_csv"

  get 'selections/:id/csv', to: "selections#csv", as: "selection_csv"
  get 'selections/:id/mail', to: "selections#mail", as: "selection_mail"
  get 'selections/:id/summary', to: "selections#summary", as: "selection_summary"
  get 'selections/:id/return', to: "selections#return", as: "selection_return"
  get 'selections/:id/etiquette', to: "selections#etiquette", as: "selection_etiquette"
  get 'carts/devis', to: "carts#devis", as: "devis"

  resources :brands
  resources :clothes
  resources :colors
  resources :tarifs
    get 'brands/:id/tarifsbybrand', to: "tarifs#tarifsbybrand", as: "tarifsbybrand"
    get 'brands/research', to: "brands#research", as: "research"

  post 'products/:id/save_price', to: "products#save_price", as: "save_price"

  # resources :sessions
  post 'sessions/display', to: "sessions#display", as: "display"
  post 'sessions/list', to: "sessions#list", as: "list"
  get 'sessions/validation', to: "sessions#validation", as: "validation"
  get 'products/:id/add_to_list', to: "products#add_to_list", as: "add_to_list"
  get 'products/:id/delete_to_list', to: "products#delete_to_list", as: "delete_to_list"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord

  def percentagebrand
    @products = Product.where(status: "à vendre")
    percentagebrand = ((@products.where(brand: self.name).count.to_f / @products.count.to_f)*100).round(2)
    return percentagebrand
  end

  def percentagebysizeandbrand(size)
    @products = Product.where(status: "à vendre")
    percentagebysizeandbrand = ((@products.where(brand: self.name, size: size).count.to_f / @products.count.to_f)*100).round(2)
    return percentagebysizeandbrand
  end

    #pg search
  include PgSearch::Model
  pg_search_scope :search_by_name,
    against: [ :name],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.order(name: :asc)
    @clothes = Clothe.order(name: :asc)
    @colors = Color.order(name: :asc)
  end

  def research
    if params[:query].present?
      @brands = Brand.search_by_name(params[:query])
    else
      @brands = Brand.all
    end
    if @brands.count == 0
      @brands = Brand.all
    end
    authorize @brands
  end

  def new
    @brand = Brand.new
    authorize @brand
  end

  def create
    @brand = Brand.new(brand_params)
    authorize @brand
    @brand.name.capitalize!
    @brand.save
    redirect_to brands_path
  end

  # def edit
  #   @brand = Brand.find(params[:id])
  # end

  # def update
  #   @brand = Brand.find(params[:id])
  #   if @brand.update(brand_params)
  #     redirect_to brand_path(@brand)
  #   else render :edit
  #   end
  # end

  def destroy
    @brand = Brand.find(params[:id])
    authorize @brand
    @brand.destroy
    redirect_to brands_path
  end

  private

  def brand_params
    params.require(:brand).permit(:name)
  end
end

app/views/brands/index.html.erb
<div class="container">
  <h2> Mes Marques & Vêtements</h2>
  <div style="width: 100%; display:flex; justify-content: space-around;">
    <%= link_to 'retour au Menu', root_path, class: "btn btn-success"%>
    <%= link_to "Retour aux fournisseurs", fournisseurs_path, class: "button-return"%>
    <% if Selection.all.count > 0 %>
      <% @selection = Selection.last %>
      <%= link_to 'Revenir à la dernière sélection',selection_path(@selection), class: "button-return"%>
    <% end %>
  </div>
  <br>
  <div style="width: 100%; display:flex; justify-content: space-around;">
    <%= link_to 'Ajouter une marque', new_brand_path, class: "button-ts"%>
    <%= link_to 'Ajouter un vêtement', new_clothe_path, class: "button-ts"%>
    <%= link_to 'Ajouter une couleur', new_color_path, class: "button-ts"%>
  </div>
  <br>
  <div style="width: 100%; display:flex; justify-content: space-around;">
    <div class="fiche_listing bg_list1">
      <% if Brand.all.count == 0 %>
        <p>Aucune marque n'est créée actuellement.</p>
      <% else %>
        <h2>Les Marques</h2>
        <% @brands.each do |brand| %>
          <div class="fiche_column">
            <div><%= brand.name %></div>
            <div><%= link_to 'X', brand_path(brand), method: :delete, class: "button-red"%></div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="fiche_listing bg_list2">
      <% if Clothe.all.count == 0 %>
        <p>Aucun vêtement n'est créée actuellement.</p>
      <% else %>
        <h2>Les Vêtements</h2>
        <% @clothes.each do |clothe| %>
          <div class="fiche_column">
            <div><%= clothe.name %></div>
            <div><%= link_to 'X', clothe_path(clothe), method: :delete, class: "button-red"%></div>
          </div>
        <% end %>
      <% end %>
    </div>
        <div class="fiche_listing bg_list3">
      <% if Color.all.count == 0 %>
        <p>Aucune couleur n'est créée actuellement.</p>
      <% else %>
        <h2>Les Couleurs</h2>
        <% @colors.each do |color| %>
          <div class="fiche_column">
            <div><%= color.name %></div>
            <div><%= link_to 'X', color_path(color), method: :delete, class: "button-red"%></div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/brands/new.html.erb
<div class="fiche_fournisseur">
  <h1>Brands#new</h1>
  <%= link_to 'retour au Menu', root_path, class: "btn btn-success"%>
  <br>
  <p>Pour créer une marque, c'est ici que ça se passe >></p>
  <br>
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-8">
        <h1>Nouvelle marque :</h1>
        <%= simple_form_for [ @brand ] do |f| %>
        <%= f.input :name, label: 'Nom de la marque', placeholder: "Jacadi, Dior, Merlinpinpin" %>
         <div class="form-button mt-2">
          <%= f.submit "Créer le produit", class: 'btn btn-primary' %>
         </div>
         <br>
       <% end %>
      </div>
    </div>
  </div>
</div>

app/views/brands/research.html.erb
<div class="search" style="margin-top: 50vh;">
  <%= form_tag research_path, method: :get, novalidate: "novalidate", class: "simple_form search"  do %>
    <div class="search-form-control form-group mt-1 mb-0">
      <%= text_field_tag :query,
          params[:query],
          class: "search-input form-control string required",
          id: "search_query",
          placeholder: "recherche une marque",
          value: ""
      %>
      <%= button_tag(type: "submit", class: "btn btn-flat") do %>
        <i class="fas fa-search"></i>
      <% end %>
    </div>
  <% end %>
</div>
<div style="margin-top: 20vh; margin-left:20vw; display: flex; flex-direction: column; align-items: start;">
    <ul style="font-weight: bolder;">Marques</ul>
    <% Brand.order(name: :asc).each do |element| %>
      <% @brand = element %>
        <%= link_to tarifsbybrand_path(@brand) do %>
          <p style="margin: auto; color: black; font-weight: bolder; padding: 16px; background-color: yellow; border-radius: 6px; width: 100px; margin-top: 8px;"><%= @brand.name %></p>
        <% end %>
    <% end %>
</div>