config/routes.rb
Rails.application.routes.draw do
  get 'justificatifs/new'
  get 'justificatifs/create'
  devise_for :users
  root to: 'pages#home'
  get 'furnishers', to: 'pages#fournisseurs'

  get 'price', to: 'pages#price'
  get 'brands/:id/pricer', to: 'pages#pricer'

  get 'stocks', to: 'pages#stocks'
  get 'panier', to: 'pages#panier'
  get 'comptabilite', to: 'pages#comptabilite'
  get 'creditdetail', to: 'pages#creditdetail'
  get 'stat', to: 'pages#stat'
  get 'fiche', to: 'pages#fiche'
  get 'repartition', to: 'pages#repartition'
  get 'repartitionage', to: 'pages#repartitionage'
  get 'repartitiongenre', to: 'pages#repartitiongenre'
  get 'venteparsku', to: 'pages#venteparsku'
  get 'inventoryage', to: 'pages#inventoryage'
  get 'pro', to: 'pages#pro'
  get 'caisse', to: 'pages#caisse'

  resources :fournisseurs do
    resources :paiements, only: [ :index, :show, :new, :create]
    resources :justificatifs, only: [:new, :create]
  end

  resources :justificatifs, only: [:edit, :update]
  post 'justificatifs/:id/don', to: "justificatifs#don", as: "don"

  resources :selections do
    resources :products, only: [ :index, :new, :create ]
  end
  resources :products, only: [ :index, :edit, :update, :destroy, :show]
    post 'products/:id/sold', to: "products#sold_status", as: "sold_status"
    post 'products/:id/sell', to: "products#tosell_status", as: "tosell_status"
    post 'products/:id/return', to: "products#return_status", as: "return_status"
    post 'products/:id/edit_price', to: "products#edit_price", as: "edit_price"
    post 'products/duplicate', to: "products#duplicate", as: "duplicate"
    post 'products/import', to: "products#import", as: "import"
    get 'products/:id/stock4pro', to: "products#stock4pro", as: "stock4pro"
    get 'products/:id/select4pro', to: "products#select4pro", as: "select4pro"
    get 'products/:id/qrcode', to: "products#qrcode", as: "qrcode"

  resources :paiements, only: [ :edit, :update, :destroy]
    post 'paiements/:id/settle', to: "paiements#settle_status", as: "settle_status"
    post 'paiements/avoir', to: "paiements#avoir", as: "avoir"
    post 'paiements/:id/edit_amount', to: "paiements#edit_amount", as: "edit_amount"

  get 'fournisseurs/:id/save_csv', to: "fournisseurs#save_csv", as: "fournisseur_save_csv"

  get 'selections/:id/csv', to: "selections#csv", as: "selection_csv"
  get 'selections/:id/mail', to: "selections#mail", as: "selection_mail"
  get 'selections/:id/summary', to: "selections#summary", as: "selection_summary"
  get 'selections/:id/return', to: "selections#return", as: "selection_return"
  get 'selections/:id/etiquette', to: "selections#etiquette", as: "selection_etiquette"
  get 'carts/devis', to: "carts#devis", as: "devis"

  resources :brands
  resources :clothes
  resources :colors
  resources :tarifs
    get 'brands/:id/tarifsbybrand', to: "tarifs#tarifsbybrand", as: "tarifsbybrand"
    get 'brands/research', to: "brands#research", as: "research"

  post 'products/:id/save_price', to: "products#save_price", as: "save_price"

  # resources :sessions
  post 'sessions/display', to: "sessions#display", as: "display"
  post 'sessions/list', to: "sessions#list", as: "list"
  get 'sessions/validation', to: "sessions#validation", as: "validation"
  get 'products/:id/add_to_list', to: "products#add_to_list", as: "add_to_list"
  get 'products/:id/delete_to_list', to: "products#delete_to_list", as: "delete_to_list"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  require 'rqrcode'
  require 'chunky_png'

  belongs_to :selection, optional: true
  has_many :items, dependent: :destroy

  monetize :price_cents

  has_one_attached :photo
  # has_one_attached :barcode
  #pg search for products
  include PgSearch::Model
  pg_search_scope :search_by_brand_id_name,
    against: [ :id, :brand, :name ],
    using: {
      tsearch: { prefix: true }
    }

  def change_status
    self.status = "vendu"
  end

  def solded
    percentage = 0.0
    solded = self.where(status: "vendu").to_f
    all = self.all.to_f
    percentage = solded / all
    return percentage
  end
0
  def qrcode
    @product = Product.find(params[:id])
    authorize @product
    @code = "https://g2m-management.herokuapp.com/products/#{@product.id.to_s}/add_to_list"
    @qrcode = RQRCode::QRCode.new(@code)

    @svg = @qrcode.as_svg(
      offset:0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 1,
      standalone: true,
      use_path: true
    )
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  require 'open-uri'
  require 'json'
  require 'rqrcode'
  require 'chunky_png'


  def index
    if params[:query].present?
      @products = Product.search_by_brand_id_name(params[:query])
      authorize @products
    else
      @products = Product.where(user_id: current_user.id).limit(30)
      authorize @products
    end
    if @products.count == 0
      @products = Product.where(user_id: current_user.id).limit(30)
      authorize @products
    end
  end

  def stock4pro
    @brand = Brand.find(params[:id])
    @products = Product.where(brand: @brand.name, status: "à vendre")
    authorize @products
  end

  def select4pro
    @cart = @current_cart
    @product = Product.find(params[:id])
    authorize @product
    @item = Item.new(product: @product, cart: @cart)
    @item.save
    flash[:notice] = "Hop! dans la musette"
    @brand = Brand.where(name: @product.brand).first.id
    redirect_to stock4pro_path(@brand)
  end

  def show
    @product = Product.find(params[:id])
    authorize @product
  end

  def new
    @selection = Selection.find(params[:selection_id])
    authorize @selection
    @product = Product.new
    authorize @product
  end

  def create
    @brands = Brand.all
    @product = Product.new(product_params)
    authorize @product
    @selection = Selection.find(params[:selection_id])
    authorize @selection
    @product.selection = @selection
    @product.user_id = @selection.user_id
    # to add a category according to name of product itself
    array1 = ["Pull", "Gilet", "Cardigan", "Sweat"]
    array2 = ["Blouse", "Chemise","Haut manches longues","Haut manches courtes", "Polo"]
    array3 = ["Body", "Pyjama", "Gigoteuse", "Peignoir", "Lot bodies"]
    array4 = ["Combinaison", "Salopette", "Bloomer Salopette", "Ensemble"]
    array5 = ["Robe", "Jupe"]
    array6 = ["Pantalon", "Legging", "Jogging"]
    array7 = ["Cap", "Manteau", "Combinaison pilote", "Blouson", "Veste", "Doudoune"]
    array8 = ["Chaussures", "Chaussons"]
    array9 = ["Short", "Bloomer"]
    array10 = ["Combinaison de ski"]
    array11 = ["Maillot de bain"]
    if array1.include?(@product.name)
      @product.category = "Pulls, Mailles"
    elsif array2.include?(@product.name)
      @product.category = "Tops"
    elsif array3.include?(@product.name)
      @product.category = "Sous vêtements, Pyjamas"
    elsif array4.include?(@product.name)
      @product.category = "Ensembles, Combinaisons"
    elsif array5.include?(@product.name)
      @product.category = "Robes, Jupes"
    elsif array6.include?(@product.name)
      @product.category = "Pantalons"
    elsif array7.include?(@product.name)
      @product.category = "Manteaux, Vestes"
    elsif array8.include?(@product.name)
      @product.category = "Chaussures, Chaussons"
    elsif array9.include?(@product.name)
      @product.category = "Shorts, Bloomers"
    elsif array10.include?(@product.name)
      @product.category = "Vêtements de ski"
    elsif array11.include?(@product.name)
      @product.category = "Maillots de bain"
    else
      @product.category = "Accessoires"
    end
    # début du pricer
    if Tarif.where(brand: @product.brand, clothe: @product.name).present?
      @product.price = Tarif.where(brand: @product.brand, clothe: @product.name).first.price
    else
      @product.price = 0
    end

    # to genrate a barcode
    # code = Product.last.id.to_i + 1
    # @product.barcode = Barby::Code128.new(code)
    # name = code.to_s +".png"
    # File.open(name, 'wb'){|f|
    #   f.write barcode.to_png(:height => 20, :margin => 5)
    # }
    # end

    if @product.save && params[:commit] == 'Créer le produit'
      redirect_to selection_path(@selection)
      flash[:notice] = "Votre produit a bien été enregistré."
    elsif @product.save && params[:commit] == 'Créer un autre produit'
      redirect_to new_selection_product_path(@selection)
      flash[:notice] = "Votre produit a bien été enregistré."
    else
      render :new
      flash[:alert] = "Veuillez compléter le formulaire s'il vous plaît."
    end
  end

  def edit
    @product = Product.find(params[:id])
    authorize @product
  end

  def update
    @product = Product.find(params[:id])
    authorize @product
    #to edit category
    array1 = ["Pull", "Gilet", "Cardigan", "Sweat"]
    array2 = ["Blouse", "Chemise","Haut manches longues","Haut manches courtes", "Polo"]
    array3 = ["Body", "Pyjama", "Gigoteuse", "Peignoir", "Lot bodies"]
    array4 = ["Combinaison", "Salopette", "Bloomer Salopette", "Ensemble"]
    array5 = ["Robe", "Jupe"]
    array6 = ["Pantalon", "Legging", "Jogging"]
    array7 = ["Cap", "Manteau", "Combinaison pilote", "Blouson", "Veste", "Doudoune"]
    array8 = ["Chaussures", "Chaussons"]
    array9 = ["Short", "Bloomer"]
    array10 = ["Combinaison de ski"]
    array11 = ["Maillot de bain"]
    if array1.include?(@product.name)
      @product.category = "Pulls, Mailles"
    elsif array2.include?(@product.name)
      @product.category = "Tops"
    elsif array3.include?(@product.name)
      @product.category = "Sous vêtements, Pyjamas"
    elsif array4.include?(@product.name)
      @product.category = "Ensembles, Combinaisons"
    elsif array5.include?(@product.name)
      @product.category = "Robes, Jupes"
    elsif array6.include?(@product.name)
      @product.category = "Pantalons"
    elsif array7.include?(@product.name)
      @product.category = "Manteaux, Vestes"
    elsif array8.include?(@product.name)
      @product.category = "Chaussures, Chaussons"
    elsif array9.include?(@product.name)
      @product.category = "Shorts, Bloomers"
    elsif array10.include?(@product.name)
      @product.category = "Vêtements de ski"
    elsif array11.include?(@product.name)
      @product.category = "Maillots de bain"
    else
      @product.category = "Accessoires"
    end
    if @product.update(product_params)
      redirect_to selection_path(@product.selection)
    else render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    authorize @product
    @product.destroy
    redirect_to selection_path(@product.selection)
  end

  def sold_status
    @product = Product.find(params[:id])
    authorize @product
    @product.status = "vendu"
    @product.save
    redirect_to selection_path(@product.selection)
  end

  def tosell_status
    @product = Product.find(params[:id])
    authorize @product
    @product.status = "à vendre"
    @product.save
    redirect_to selection_path(@product.selection)
  end

  def return_status
    @product = Product.find(params[:id])
    authorize @product
    @product.status = "retourné"
    @product.save
    redirect_to selection_path(@product.selection)
  end

  def edit_price
    @product = Product.find(params[:id])
    authorize @product
  end

  def save_price
    @tarif = Tarif.new
    @product = Product.find(params[:id])
    authorize @product
    @tarif.clothe = @product.name
    @tarif.brand = @product.brand
    @tarif.price = @product.price
    @tarif.save!
    redirect_to selection_path(@product.selection)
    flash[:notice] = "Le prix a été enregistré."
  end

  def change_price
    @product = Product.find(params[:id])
    authorize @product
    @product.update(price_params)
    @product.save
    redirect_to selection_path(@product.selection)
    flash[:notice] = "Votre prix a bien été modifié."
  end

  def duplicate
    @product = Product.new
    authorize @product
    @last_product = Product.last
    @product.name = @last_product.name
    @product.brand = @last_product.brand
    @product.size = @last_product.size
    @product.color = @last_product.color
    @product.genre = @last_product.genre
    @product.selection = @last_product.selection
    @product.user_id = @last_product.selection.user_id
    @product.price = @last_product.price
    @product.category = @last_product.category
    @product.season = @last_product.season
    @product.comment = @last_product.comment

    @product.save!
    redirect_to selection_path(@product.selection)
    flash[:notice] = "Votre produit a été dupliqué."
  end

  def import
    # start with since_id = 0 and number of products parsed = 0
    number = 0
    since_id = 0
    # Get products.count with API SHOPIFY
    url = "https://#{ENV['SHOPIFY_API_KEY']}:#{ENV['SHOPIFY_API_PASSWORD']}@#{ENV['SHOPIFY_API_SHOP']}.myshopify.com/admin/api/2020-10/products/count.json"
    count_serialized = RestClient.get(url)
    result = JSON.parse(count_serialized)
    total = result["count"]
    #while sum of products called with API not equal to products.count
    while number < total
      url = "https://#{ENV['SHOPIFY_API_KEY']}:#{ENV['SHOPIFY_API_PASSWORD']}@#{ENV['SHOPIFY_API_SHOP']}.myshopify.com/admin/api/2020-10/products.json?since_id=#{since_id}"
      user_serialized = RestClient.get(url)
      user = JSON.parse(user_serialized)
      # get status of each product, add each product to number and get last product.id to update since_id
      user["products"].each do |product|
        qty = nil
        sku = product["variants"].first.values_at("sku").first
        if Product.where(id: sku).present? && product["variants"].first.values_at("inventory_quantity").first == 0
          @product = Product.where(id: sku).first
          @product.status = "vendu"
          @product.save!
        end
        number += 1
        since_id = product["id"] + 1
      end
      skip_authorization
    end
    redirect_to products_path
    flash[:notice] = "le traitement est terminé"
  end

  def qrcode
    @product = Product.find(params[:id])
    authorize @product
    @code = "https://g2m-management.herokuapp.com/products/#{@product.id.to_s}/add_to_list"
    @qrcode = RQRCode::QRCode.new(@code)

    @svg = @qrcode.as_svg(
      offset:0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 1,
      standalone: true,
      use_path: true
    )
  end

  def add_to_list
    @product = Product.find(params[:id])

app/views/products/edit.html.erb
<div class="container">
  <%= link_to 'retour à la sélection', selection_path(@product.selection), class: "btn btn-success"%>
  <div class="row">
    <div class="col-12 col-md-8">
      <h1>Modifier ce produit</h1>
      <%= simple_form_for [ @selection, @product ] do |f| %>
        <% array_brand =  []%>
        <% array_clothe =  []%>
        <% array_color =  []%>
        <% Brand.all.each do |brand| %>
        <%   array_brand << brand.name %>
        <% end %>
        <% Clothe.all.each do |clothe| %>
          <%   array_clothe << clothe.name %>
        <% end %>
        <% Color.all.each do |color| %>
          <%   array_color << color.name %>
        <% end %>
        <%= f.input :name, label: "Nom du vêtement",collection:  array_clothe %>
        <%= f.input :brand, label: "Marque",collection: array_brand %>
        <%= f.input :size, label: "Taille",collection: ['0 mois', '1 mois','3 mois','3-6 mois','6 mois','6-9 mois','9 mois','9-12 mois','12 mois','12-18 mois','18 mois','18-24 mois','2 ans', '2-3 ans','3 ans','3-4 ans', '4 ans', '5 ans', '6 ans', '7 ans', '8 ans', '9 ans', '10 ans', '11 ans', '12 ans', '14 ans', 'Pointure 15', 'Pointure 16', 'Pointure 17', 'Pointure 18', 'Pointure 19', 'Pointure 20', 'Pointure 21', 'Pointure 22', 'Pointure 23', 'Pointure 24', 'Pointure 25', 'Pointure 26', 'Pointure 27', 'Pointure 28', 'Pointure 29', 'Pointure 30', 'Pointure 31', 'Pointure 32', 'Pointure 33', 'Pointure 34', 'N/A']%>
        <%= f.input :genre, label: "Genre",collection: ['Fille', 'Garçon', 'Mixte'] %>
        <%= f.input :color, label: "Sa couleur",collection: array_color %>
        <%= f.input :season, label: "Saison",collection: ['Printemps/Eté', 'Automne/Hiver'] %>
        <%= f.input :comment, label: "Choisir l'état", collection: ['Neuf avec étiquette', 'Excellent état', 'Bon état'] %>
        <%= f.input :commentaire, label: "Ajouter un commentaire"%>

        <%= f.association :selection, input_html: { class: "beautiful-dropdown" }, include_hidden: false, :label_method => lambda { |selection| "#{selection.fournisseur.firstname} #{selection.fournisseur.lastname}" } %>
       <div class="d-flex mb-2">
         <%= f.input :photo, label: 'Ajoutez une photo', as: :file %>
       </div>
       <div class="form-button mt-2">
        <%= f.submit "Modifier le produit", class: 'btn btn-primary' %>
       </div>
       <br>
     <% end %>
    </div>
  </div>
</div>

app/views/products/edit_price.html.erb
<div class="container mt-5">
  <%= link_to 'retour à la sélection', selection_path(@product.selection), class: "btn btn-success"%>
   <div class="container form-container">
     <%= simple_form_for(@product) do |f| %>
      <p>Modifiez le prix TTC de ce produit</p>
       <div class="form-top">
         <%= f.number_field :price_cents, label: "Quelle somme en cents ? ex : pour 10 €, taper 1000 (NB >> on va essayer de modifier en €)", placeholder: 0%>
       </div>
       <div class="btn btn-primary">
        <%= f.submit "Soumettre", class: 'btn btn-contact'%>
       </div>
     <% end %>
   </div>
</div>

app/views/products/index.html.erb
<div class="stocks">
  <%= link_to 'Retour au Menu', root_path, class: "button-sm"%>
  <%= link_to 'Inventaire par date', inventoryage_path, class: "button-sm"%>
<!--   <%= link_to 'Importer ventes', import_path, method: :post, class: "button-red", id:"margin-top-button"%> -->
  <div class="search mt-2">
    <%= form_tag products_path, method: :get, novalidate: "novalidate", class: "simple_form search"  do %>
      <div class="search-form-control form-group mt-1 mb-0">
        <%= text_field_tag :query,
            params[:query],
            class: "search-input form-control string required",
            id: "search_query",
            placeholder: "chercher un produit par son nom, sa marque ou son identifiant",
            value: ""
        %>
        <%= button_tag(type: "submit", class: "btn btn-flat") do %>
          <i class="fas fa-search"></i>
        <% end %>
      </div>
    <% end %>
  </div>

  <table class="products_table">
    <tr id="product-bg">
      <td>N°</td>
      <td>Vêtements</td>
      <td>Marque</td>
      <td>Déposant</td>
      <td>Prix TTC</td>
      <td>Photo</td>
      <td>MAJ prix</td>
      <td>Editer</td>
      <td>Supprimer</td>
      <td>Statut</td>
      <td>Vendu ?</td>
    </tr>
    <% @products.order(:id).each do |element| %>
      <% if element.status == "vendu" %>
        <tr id="product-details-vendu">
          <td><%= element.id %></td>
          <td><%= element.name %></td>
          <td><%= element.brand %></td>
          <% if element.selection.present? && element.selection.fournisseur.present? %>
            <td><%= element.selection.fournisseur.firstname%> <%= element.selection.fournisseur.lastname%></td>
          <% else %>
            <td><i class="fas fa-ban" style="color: #9E2725;"></i></td>
          <% end %>
          <td><%= element.price %>€</td>
          <td>
            <% if element.photo.present?%>
              <%= link_to product_path(element) do %>
                <i class="fas fa-camera-retro"></i>
              <% end %>
            <% else %>
              <i class="fas fa-ban" style="color: #9E2725;"></i>
            <% end %>
          </td>
          <td>
            <% if element.status == "à vendre" %>
              <%= link_to '€', edit_price_path(element), method: :post %>
            <% else %>
              <i class="fas fa-ban" style="color: #9E2725;"></i>
            <% end %>
          </td>
          <td>
            <% if element.status == "à vendre" %>
              <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_product_path(element)%>
            <% else %>
              <i class="fas fa-ban" style="color: #9E2725;"></i>
            <% end %>
          </td>
          <td>
            <% if element.status == "à vendre" %>
              <%= link_to '<i class="fas fa-trash"></i>'.html_safe, product_path(element), method: :delete, data: {confirm: "Vous êtes sûre?"} %>
            <% else %>
              <i class="fas fa-ban" style="color: #9E2725;"></i>
            <% end %>
          </td>
          <td><%= element.status %></td>
          <td>
            <%= link_to '<i class="fas fa-cart-arrow-down"></i>'.html_safe, sold_status_path(element), method: :post, style:"color: green;" %> / <%= link_to '<i class="fas fa-undo"></i>'.html_safe, tosell_status_path(element), method: :post, style:"color: #F6AE3B;" %>
          </td>
        </tr>
      <% else %>
        <tr id="product-details">
          <td><%= element.id %></td>
          <td><%= element.name %></td>
          <td><%= element.brand %></td>
          <% if element.selection.present? && element.selection.fournisseur.present? %>
            <td><%= element.selection.fournisseur.firstname%> <%= element.selection.fournisseur.lastname%></td>
          <% else %>
            <td><i class="fas fa-ban" style="color: #9E2725;"></i></td>
          <% end %>
          <td><%= element.price %>€</td>
          <td>
            <% if element.photo.present?%>
              <%= link_to product_path(element) do %>
                <i class="fas fa-camera-retro"></i>
              <% end %>
            <% else %>
              <i class="fas fa-ban" style="color: #9E2725;"></i>
            <% end %>
          </td>
          <td>
            <% if element.status == "à vendre" %>
              <%= link_to '€', edit_price_path(element), method: :post %>
            <% else %>
              <i class="fas fa-ban" style="color: #9E2725;"></i>
            <% end %>
          </td>
          <td>
            <% if element.status == "à vendre" %>
              <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_product_path(element)%>
            <% else %>
              <i class="fas fa-ban" style="color: #9E2725;"></i>
            <% end %>
          </td>
          <td>
            <% if element.status == "à vendre" %>
              <%= link_to '<i class="fas fa-trash"></i>'.html_safe, product_path(element), method: :delete, data: {confirm: "Vous êtes sûre?"} %>
            <% else %>
              <i class="fas fa-ban" style="color: #9E2725;"></i>
            <% end %>
          </td>
          <td><%= element.status %></td>
          <td>
            <%= link_to '<i class="fas fa-cart-arrow-down"></i>'.html_safe, sold_status_path(element), method: :post, style:"color: green;" %> / <%= link_to '<i class="fas fa-undo"></i>'.html_safe, tosell_status_path(element), method: :post, style:"color: #F6AE3B;" %>
          </td>
        </tr>
      <% end %>

    <% end %>
  </table>
</div>

app/views/products/new.html.erb
<div class="container mt-5">
  <div class="buttons-fournisseurs">
    <%= link_to 'Retour à la sélection', selection_path(@selection), class: "btn btn-success"%>
    <%= link_to 'Créer une marque', new_brand_path, class: "button-red"%>
    <%= link_to 'Créer un vêtement', new_clothe_path, class: "button-sm"%>
    <%= link_to 'Créer une couleur', new_color_path, class: "button-red"%>
    <% if @selection.products.count > 0 %>
      <% product = @selection.products.last %>
      <%= link_to 'Revenir au dernier produit',edit_product_path(product), class: "button"%>
    <% end %>
  </div>
  <div class="row">
    <div class="col-12 col-md-8">
      <h1>Nouveau produit</h1>
      <%= simple_form_for [ @selection, @product ] do |f| %>
        <% array_brand =  []%>
        <% array_clothe =  []%>
        <% array_color =  []%>
        <% Brand.all.each do |brand| %>
        <%   array_brand << brand.name %>
        <% end %>
        <% Clothe.all.each do |clothe| %>
          <%   array_clothe << clothe.name %>
        <% end %>
        <% Color.all.each do |color| %>
          <%   array_color << color.name %>
        <% end %>
        <%= f.input :name, label: "Nom du vêtement",collection:  array_clothe %>
        <%= f.input :brand, label: "Marque",collection: array_brand %>
        <%= f.input :size, label: "Taille",collection: ['0 mois', '1 mois','3 mois','3-6 mois','6 mois','6-9 mois','9 mois','9-12 mois','12 mois','12-18 mois','18 mois','18-24 mois','2 ans', '2-3 ans','3 ans','3-4 ans', '4 ans', '5 ans', '6 ans', '7 ans', '8 ans', '9 ans', '10 ans', '11 ans', '12 ans', '14 ans', 'Pointure 15', 'Pointure 16', 'Pointure 17', 'Pointure 18', 'Pointure 19', 'Pointure 20', 'Pointure 21', 'Pointure 22', 'Pointure 23', 'Pointure 24', 'Pointure 25', 'Pointure 26', 'Pointure 27', 'Pointure 28', 'Pointure 29', 'Pointure 30', 'Pointure 31', 'Pointure 32', 'Pointure 33', 'Pointure 34', 'N/A']%>
        <%= f.input :genre, label: "Genre",collection: ['Fille', 'Garçon', 'Mixte'] %>
        <%= f.input :color, label: "Sa couleur",collection: array_color %>
        <%= f.input :season, label: "Saison",collection: ['Printemps/Eté', 'Automne/Hiver'] %>
        <%= f.input :comment, label: "Choisir l'état", collection: ['Neuf avec étiquette', 'Excellent état', 'Bon état'] %>
        <%= f.input :commentaire, label: "Ajouter un commentaire"%>
        <div class="d-flex mb-2">
          <%= f.input :photo, label: 'Ajoutez une photo', as: :file %>
        </div>
         <div class="form-button mt-2 mb-2">
          <%= f.submit "Créer le produit", class: 'button-red', style:"height: 40px !important;" %>
          <%= f.submit "Créer un autre produit", class: 'button-sm', style:"height: 40px !important;" %>
         </div>
     <% end %>
    </div>
  </div>
</div>

app/views/products/qrcode.html.erb
<h1>QR code generator</h1>
<div style='margin: 10vh;'>
  <%= @svg.html_safe %>
</div>

app/views/products/show.html.erb
<div class="modal">
  <div class="modal-wrapper">
    <% if @product.photo.present? %>
      <%= link_to 'X', :back %>
      <%= cl_image_tag @product.photo.key %>
    <% else %>
      <%= link_to 'X', :back%>
      <p>le produit n°<%= @product.id %> n'a pas encore d'image.</p>
    <% end %>
  </div>
</div>

app/views/products/stock4pro.html.erb
<div class="stocks4pro">
  <%= link_to 'Retour au Menu', root_path, class: "button-sm"%>
  <%= link_to 'Retour aux marques', pro_path, class: "button-red mt-2"%>
  <%= link_to 'Demandez un devis', devis_path, class: "button-red mt-2"%>

  <table class="products_table">
    <tr id="product-bg">
      <td>Vêtements</td>
      <td>Marque</td>
      <td>Prix HT</td>
      <td>Photo</td>
      <td>Sélectionnez</td>
    </tr>
    <% @products.each do |product| %>
      <% if (Date.today - product.created_at.to_date).to_i > 44 %>
        <tr id="product-details">
          <td><%= product.name %></td>
          <td><%= product.brand %></td>
          <td><%= product.price/2 %>€</td>
          <td>
            <% if product.photo.present?%>
              <%= link_to product_path(product) do %>
                <i class="fas fa-camera-retro"></i>
              <% end %>
            <% else %>
              <i class="fas fa-ban" style="color: #9E2725;"></i>
            <% end %>
          </td>
          <td><%= link_to '<i class="fas fa-cart-plus"></i>'.html_safe, select4pro_path(product), style:"color: green;" %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>